<a href="https://colab.research.google.com/github/brunokobi/Reconhecimento_Padrao/blob/main/compEnsembles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Comparação de ensembles**

In [ ]:
from sklearn.datasets import fetch_olivetti_faces
X, y = fetch_olivetti_faces(return_X_y=True)
X.shape, y.shape

((400, 4096), (400,))

In [ ]:
from sklearn.model_selection import train_test_split
X_tr, X_te, y_tr, y_te = train_test_split(X, y, random_state=42)
X_tr.shape, X_te.shape, y_tr.shape, y_te.shape

((300, 4096), (100, 4096), (300,), (100,))

# **KNN sem ajuste parametros**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
modelo = KNeighborsClassifier()
modelo.fit(X_tr, y_tr)
knn_pr = modelo.predict(X_te)
knnhits = knn_pr == y_te
knnhits, sum(knnhits)/len(knnhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True, False, False,  True,  True, False,  True,
        False, False,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True, False,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]), 0.83)

# **Ajuste paramentros KNN**

In [ ]:
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler
    from sklearn.model_selection import GridSearchCV
    pipe = Pipeline([    
        ('knn', KNeighborsClassifier()) 
    ])
    params = {
        # 'knn__algorithm' : ['ball_tree','kd_tree', 'brute'],
        # 'knn__n_neighbors': [3, 5, 10],
        'knn__leaf_size':[10,15,20],
        # 'knn__weights':['distance','uniform'],
        # 'knn__metric':['cityblock', 'cosine', 'euclidean', 'l1', 'l2', 'manhattan', 'braycurtis','canberra', 'chebyshev', 'correlation', 'minkowski'],
        'knn__weights':['distance'],
        'knn__metric':['cityblock'],
        'knn__algorithm' : ['ball_tree'],
        'knn__n_neighbors': [3],
        
    }
    clf = GridSearchCV(estimator=pipe,           
                      param_grid=params, 
                      cv=5,
                      return_train_score=True) # Turn on cv train scores
    clf.fit(X_tr, y_tr)  
    print('\nMelhor Ajuste:',clf.best_estimator_,'score:',clf.best_score_)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  UserWarning,



Melhor Ajuste: Pipeline(steps=[('knn',
                 KNeighborsClassifier(algorithm='ball_tree', leaf_size=10,
                                      metric='cityblock', n_neighbors=3,
                                      weights='distance'))]) score: 0.8866666666666667


# **KNN parametros ajustados**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
modelo = KNeighborsClassifier(algorithm='ball_tree', leaf_size=10,
                                      metric='cityblock', n_neighbors=3,
                                      weights='distance')
modelo.fit(X_tr, y_tr)
knn_pr = modelo.predict(X_te)
knnhits = knn_pr == y_te
knnhits, sum(knnhits)/len(knnhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]), 0.92)

# **Naive Bayes sem ajuste parametros**

In [ ]:
from sklearn.naive_bayes import GaussianNB
modelo = GaussianNB()
modelo.fit(X_tr, y_tr)
gnb_pr = modelo.predict(X_te)
gnbhits = gnb_pr == y_te
gnbhits, sum(gnbhits)/len(gnbhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True, False,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True, False,  True, False,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True, False,  True,  True,  True,  True,
        False]), 0.81)

# **Ajuste parametros Naive Bayes**

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
pipe = Pipeline([        
    ('nb', GaussianNB()) 
])
params = {    
    'nb__var_smoothing': [1e-4, 1e-3, 1e-2, 0.10, 0.50, 1.0],  
}
clf = GridSearchCV(estimator=pipe,           
                  param_grid=params, 
                  cv=5,
                  return_train_score=True) # Turn on cv train scores
clf.fit(X_tr, y_tr)
print('\nMelhor Ajuste:',clf.best_estimator_,'score:',clf.best_score_)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  UserWarning,



Melhor Ajuste: Pipeline(steps=[('nb', GaussianNB(var_smoothing=0.1))]) score: 0.8866666666666667


# **Naive Bayes parametros ajustados**

In [ ]:
from sklearn.naive_bayes import GaussianNB
modelo = GaussianNB(var_smoothing=0.1)
modelo.fit(X_tr, y_tr)
gnb_pr = modelo.predict(X_te)
gnbhits = gnb_pr == y_te
gnbhits, sum(gnbhits)/len(gnbhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]), 0.94)

# **Perceptron sem ajuste parametros**

In [ ]:
from sklearn.linear_model import Perceptron
modelo = Perceptron()
modelo.fit(X_tr, y_tr)
per_pr = modelo.predict(X_te)
perhits = per_pr == y_te
perhits, sum(perhits)/len(perhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True, False,  True,  True, False, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True, False,  True, False,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
         True, False,  True,  True,  True,  True, False,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
        False, False,  True,  True,  True,  True, False,  True, False,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True, False,  True,  True,
        False]), 0.78)

# **Ajuste parametros Perceptron**

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
pipe = Pipeline([       
    ('pe', Perceptron()) 
])
params = {    
    # 'pe__penalty': ['l2','l1','elasticnet','None'],
    # 'pe__alpha': [1e-4, 1e-3, 1e-2, 0.10, 0.50, 1.0],  
    # 'pe__max_iter': [50,100,500,1000],    
    # 'pe__tol': [1e-4, 1e-3, 1e-2, 0.10, 0.50, 1.0],   
    # 'pe__shuffle': [True,False],
    # 'pe__early_stopping': [True,False],    
    # 'pe__verbose':[1e-4, 1e-3, 1e-2, 0.10, 0.50, 1.0],
    # 'pe__eta0':[0.50, 1.0, 1.5],   
    # 'pe__n_jobs':[0, 1, 5],
    # 'pe__validation_fraction':[1e-4, 1e-3, 1e-2, 0.10, 0.50, 1.0],
    'pe__penalty': ['l2'],
    'pe__validation_fraction':[1e-4],
    'pe__max_iter': [50],  
    'pe__eta0':[0.50], 
    'pe__verbose':[1e-4],    
    
       
}
clf = GridSearchCV(estimator=pipe,           
                  param_grid=params, 
                  cv=5,
                  return_train_score=True) # Turn on cv train scores
clf.fit(X_tr, y_tr) 
print('\nMelhor Ajuste:',clf.best_estimator_,'score:',clf.best_score_)


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  UserWarning,
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  40 out of  40 | elapsed:    0.5s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  40 out of  40 | elapsed:    0.6s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  40 out of  40 | elapsed:    0.6s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  40 out of  40 | elapsed:    0.5s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  40 out of  40 | elapsed:    0.5s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend wit


Melhor Ajuste: Pipeline(steps=[('pe',
                 Perceptron(eta0=0.5, max_iter=50, penalty='l2',
                            validation_fraction=0.0001, verbose=0.0001))]) score: 0.7699999999999999


[Parallel(n_jobs=1)]: Done  40 out of  40 | elapsed:    0.7s finished


# **Perceptron sem ajuste parametros**

In [ ]:
from sklearn.linear_model import Perceptron
modelo =  Perceptron(eta0=0.5, max_iter=50, penalty='l2',validation_fraction=0.0001, verbose=0.0001)
modelo.fit(X_tr, y_tr)
per_pr = modelo.predict(X_te)
perhits = per_pr == y_te
perhits, sum(perhits)/len(perhits)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  40 out of  40 | elapsed:    0.7s finished


(array([ True,  True, False,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True, False,  True,  True, False,  True,  True,
         True,  True,  True, False, False,  True,  True, False, False,
         True, False,  True,  True,  True, False,  True,  True,  True,
         True, False, False,  True, False,  True, False,  True,  True,
        False,  True, False, False,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True, False,  True, False,
         True, False,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True, False,  True,  True, False,  True,  True,
         True]), 0.73)

In [ ]:
import numpy as np
hits = np.stack((knnhits, gnbhits, perhits))


In [ ]:
y_pr = np.stack((knn_pr, gnb_pr, per_pr))


In [ ]:
from scipy import stats
y_pr = stats.mode(y_pr)[0][0]
vohits = y_pr == y_te
vohits, sum(vohits)/len(vohits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]), 0.89)

**Combinação de classificadores**

In [ ]:
from sklearn.ensemble import VotingClassifier
modelo = VotingClassifier([
    ('knn', KNeighborsClassifier(algorithm='brute', metric='correlation',weights='distance')),
    ('naivebayes',GaussianNB(var_smoothing=0.1)),
    ('perceptron', Perceptron(eta0=0.5, max_iter=50, penalty='l2',validation_fraction=0.0001, verbose=0.0001))
])
modelo.fit(X_tr, y_tr)
vo_pr = modelo.predict(X_te)
vohits = vo_pr == y_te
vohits, sum(vohits)/len(vohits)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  40 out of  40 | elapsed:    0.7s finished


(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]), 0.92)

In [ ]:
from sklearn.ensemble import VotingClassifier
modelo = VotingClassifier([
    ('knn1', KNeighborsClassifier(1)),
    ('knn2', KNeighborsClassifier(5)),
    ('knn3', KNeighborsClassifier(algorithm='brute', metric='correlation',weights='distance')),
])
modelo.fit(X_tr, y_tr)
vo_pr = modelo.predict(X_te)
vohits = vo_pr == y_te
vohits, sum(vohits)/len(vohits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
        False, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
        False,  True, False,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]), 0.88)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
modelo = VotingClassifier([
    ('knn', KNeighborsClassifier(algorithm='brute', metric='correlation',weights='distance')),
    ('naivebayes', GaussianNB(var_smoothing=0.1)),
    ('arvore', DecisionTreeClassifier())
])
modelo.fit(X_tr, y_tr)
vo_pr = modelo.predict(X_te)
vohits = vo_pr == y_te
vohits, sum(vohits)/len(vohits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]), 0.89)

In [ ]:
modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(X_tr, y_tr)
dt_pr = modelo.predict(X_te)
dthits = dt_pr == y_te
dthits, sum(dthits)/len(dthits)

(array([False,  True, False,  True,  True, False,  True,  True,  True,
        False, False,  True,  True, False, False, False, False, False,
         True, False,  True, False, False, False, False, False, False,
        False,  True, False, False,  True, False, False, False, False,
        False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False,  True, False,  True,  True, False,
         True, False, False, False,  True,  True,  True,  True, False,
        False, False,  True,  True, False, False, False,  True, False,
        False, False,  True,  True, False, False, False,  True, False,
        False, False,  True, False,  True,  True, False, False,  True,
         True,  True,  True,  True,  True, False, False,  True, False,
        False]), 0.4)

**Diversificação por reamostragem**

In [ ]:
from sklearn.ensemble import BaggingClassifier
modelo = BaggingClassifier(random_state=42)
modelo.fit(X_tr, y_tr)
bag_pr = modelo.predict(X_te)
baghits = bag_pr == y_te
baghits, sum(baghits)/len(baghits)

(array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        False, False,  True,  True, False,  True, False, False,  True,
         True,  True, False,  True, False, False,  True, False,  True,
         True,  True,  True, False,  True,  True,  True, False, False,
        False,  True, False, False, False,  True, False,  True, False,
         True,  True,  True,  True, False, False,  True,  True, False,
         True, False, False, False,  True,  True,  True,  True, False,
        False,  True, False,  True, False,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True, False,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True, False,  True,
        False]), 0.64)

In [ ]:
modelo = BaggingClassifier(DecisionTreeClassifier(), random_state=42)
modelo.fit(X_tr, y_tr)
bag_pr = modelo.predict(X_te)
baghits = bag_pr == y_te
baghits, sum(baghits)/len(baghits)

(array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        False, False,  True,  True, False,  True, False, False,  True,
         True,  True, False,  True, False, False,  True, False,  True,
         True,  True,  True, False,  True,  True,  True, False, False,
        False,  True, False, False, False,  True, False,  True, False,
         True,  True,  True,  True, False, False,  True,  True, False,
         True, False, False, False,  True,  True,  True,  True, False,
        False,  True, False,  True, False,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True, False,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True, False,  True,
        False]), 0.64)

**Aumentando a aleatoriedade para aumentar a diversidade**

In [ ]:
modelo = BaggingClassifier(DecisionTreeClassifier(splitter='random'), random_state=42)
modelo.fit(X_tr, y_tr)
bag_pr = modelo.predict(X_te)
baghits = bag_pr == y_te
baghits, sum(baghits)/len(baghits)

NameError: ignored

In [ ]:
modelo = BaggingClassifier(DecisionTreeClassifier(splitter='random'), n_estimators=100, random_state=42)
modelo.fit(X_tr, y_tr)
bag_pr = modelo.predict(X_te)
baghits = bag_pr == y_te
baghits, sum(baghits)/len(baghits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True, False,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]), 0.89)

**Random Forest é um Bagging de Árvores de Decisão**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
modelo = RandomForestClassifier(random_state=42)
modelo.fit(X_tr, y_tr)
rf_pr = modelo.predict(X_te)
rfhits = rf_pr == y_te
rfhits, sum(rfhits)/len(rfhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True, False,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True, False, False,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]), 0.88)

# **Ajuste paramentros Random Forest**

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
pipe = Pipeline([        
    ('rf', RandomForestClassifier(random_state=42)) 
])
params = {    
    'rf__n_estimators': [10,50, 100],
    'rf__criterion': ['gini', 'entropy', 'log_loss'], 
    'rf__bootstrap': [True, False],
    '
}
clf = GridSearchCV(estimator=pipe,           
                  param_grid=params, 
                  cv=5,
                  return_train_score=True) # Turn on cv train scores
clf.fit(X_tr, y_tr)
print('\nMelhor Ajuste:',clf.best_estimator_,'score:',clf.best_score_)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  UserWarning,



Melhor Ajuste: Pipeline(steps=[('rf',
                 RandomForestClassifier(bootstrap=False, criterion='entropy',
                                        max_features=0.75, random_state=42))]) score: 0.7033333333333333


# **Random Forest Ajustado**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
modelo = RandomForestClassifier(random_state=42,criterion='entropy',bootstrap=False)
modelo.fit(X_tr, y_tr)
rf_pr = modelo.predict(X_te)
rfhits = rf_pr == y_te
rfhits, sum(rfhits)/len(rfhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]), 0.95)

**Regularização do Bagging**

In [ ]:
modelo = BaggingClassifier(DecisionTreeClassifier(splitter='random'), n_estimators=100, max_features=0.15, random_state=42)
modelo.fit(X_tr, y_tr)
bag_pr = modelo.predict(X_te)
baghits = bag_pr == y_te
baghits, sum(baghits)/len(baghits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]), 0.94)

**Florestas extremamente aleatórias**

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
modelo = ExtraTreesClassifier(random_state=42)
modelo.fit(X_tr, y_tr)
et_pr = modelo.predict(X_te)
ethits = et_pr == y_te
ethits, sum(ethits)/len(ethits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]), 0.95)

# **Ajuste paramentros Arvore extra**

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
pipe = Pipeline([        
    ('et', ExtraTreesClassifier(random_state=42)) 
])
params = {    
    'et__n_estimators': [10,50, 100],
    'et__criterion': ['gini', 'entropy', 'log_loss'],
    'et__max_features': ['sqrt', 'log2', 'None'],
}
clf = GridSearchCV(estimator=pipe,           
                  param_grid=params, 
                  cv=5,
                  return_train_score=True) # Turn on cv train scores
clf.fit(X_tr, y_tr)
print('\nMelhor Ajuste:',clf.best_estimator_,'score:',clf.best_score_)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
75 fits failed out of a total of 135.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
45 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py", line 394, in fit
    self._final_estimator.fit(Xt, y, **fit_


Melhor Ajuste: Pipeline(steps=[('et',
                 ExtraTreesClassifier(max_features='sqrt', random_state=42))]) score: 0.9433333333333334


**Boosting**

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
modelo = AdaBoostClassifier(random_state=42)
modelo.fit(X_tr, y_tr)
ab_pr = modelo.predict(X_te)
abhits = ab_pr == y_te
abhits, sum(abhits)/len(abhits)

(array([False, False, False, False, False, False,  True, False, False,
        False, False, False,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False,  True, False,  True, False,  True, False, False,
        False, False, False, False,  True, False, False, False, False,
         True, False,  True, False, False, False,  True, False,  True,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False,
        False, False,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False,
        False]), 0.13)

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
modelo = AdaBoostClassifier(DecisionTreeClassifier(max_depth=25, splitter='random'), learning_rate=0.15, random_state=42)
modelo.fit(X_tr, y_tr)
ab_pr = modelo.predict(X_te)
abhits = ab_pr == y_te
abhits, sum(abhits)/len(abhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]), 0.93)

In [ ]:
from xgboost import XGBClassifier
modelo = XGBClassifier(use_label_encoder=False, random_state=42)
modelo.fit(X_tr, y_tr)
xgb_pr = modelo.predict(X_te)
xgbhits = xgb_pr == y_te
xgbhits, sum(xgbhits)/len(xgbhits)

(array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        False,  True,  True,  True, False,  True,  True, False, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True, False, False,  True,  True,  True,  True, False,
        False, False,  True,  True, False,  True, False,  True, False,
        False,  True,  True,  True,  True, False,  True,  True, False,
         True,  True, False, False,  True,  True,  True,  True, False,
        False,  True, False,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True, False, False,  True, False,
        False, False,  True,  True,  True,  True,  True, False, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True]), 0.68)

In [ ]:
from xgboost import XGBClassifier
modelo = XGBClassifier(colsample_bynode=0.01, learning_rate=0.15, random_state=42)
modelo.fit(X_tr, y_tr)
xgb_pr = modelo.predict(X_te)
xgbhits = xgb_pr == y_te
xgbhits, sum(xgbhits)/len(xgbhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True, False,  True,  True,
         True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]), 0.93)

In [ ]:
import warnings
warnings.filterwarnings('ignore')

sem ajuste

In [ ]:
from sklearn.ensemble import StackingClassifier

voting = VotingClassifier([
    #parametros ajustados
        ('knn', KNeighborsClassifier()),
        ('naivebayes', GaussianNB()),
        ('perceptron', Perceptron())
    ])

modelo = StackingClassifier([
    ('voting', voting),
    ('extratrees', ExtraTreesClassifier(random_state=42)),
    ('randomforest', RandomForestClassifier(random_state=42))
], cv=3, passthrough=True)

modelo.fit(X_tr, y_tr) 
sc_pr = modelo.predict(X_te)
schits = sc_pr == y_te
schits, sum(schits)/len(schits)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]), 0.95)

com ajuste

In [ ]:
from sklearn.ensemble import StackingClassifier

voting = VotingClassifier([
    #parametros ajustados
        ('knn', KNeighborsClassifier(algorithm='ball_tree', leaf_size=10,
                                      metric='cityblock', n_neighbors=3,
                                      weights='distance')),
        ('naivebayes', GaussianNB(var_smoothing=0.1)),
        ('perceptron', Perceptron(eta0=0.5, max_iter=50, penalty='l2',validation_fraction=0.0001, verbose=0.0001))
    ])

modelo = StackingClassifier([
    ('voting', voting),
    ('extratrees', ExtraTreesClassifier(random_state=42)),
    ('randomforest', RandomForestClassifier(random_state=42,criterion='entropy',bootstrap=False))
], cv=3, passthrough=True)

modelo.fit(X_tr, y_tr) 
sc_pr = modelo.predict(X_te)
schits = sc_pr == y_te
schits, sum(schits)/len(schits)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  40 out of  40 | elapsed:    0.7s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  40 out of  40 | elapsed:    0.5s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  40 out of  40 | elapsed:    0.4s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  40 out of  40 | elapsed:    0.4s finished
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    h

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]), 0.94)

In [ ]:
modelo = StackingClassifier([
    ('randomforest42', RandomForestClassifier(random_state=42)),
    ('randomforest43', RandomForestClassifier(random_state=43)),
    ('randomforest44', RandomForestClassifier(random_state=44))
], cv=3, passthrough=True)

modelo.fit(X_tr, y_tr) 
sc_pr = modelo.predict(X_te)
schits = sc_pr == y_te
schits, sum(schits)/len(schits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]), 0.95)